

export enum ProcessingStatus {
  IDLE = 'IDLE',
  PENDING = 'PENDING', // Waiting in queue
  PROCESSING = 'PROCESSING', // Sending to API
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  ABORTED = 'ABORTED', // New: User cancelled
}

export type QualityLevel = 'low' | 'medium' | 'high';

export interface PhotoTask {
  id: string;
  file: File;
  previewUrl: string;
  maskBlob?: Blob; // The black/white mask generated by canvas
  customPrompt?: string; // User instructions
  spaceType?: string; // NEW: Specific room type (e.g. "Living Room", "Bedroom")
  resultUrl?: string; // The URL of the edited image from API
  status: ProcessingStatus;
  errorMessage?: string;
  statusMessage?: string; // New field for realtime status updates
}

export interface BrushSettings {
  size: number;
  color: string; // Visual color (e.g., semi-transparent red)
}

// --- Admin / User Types ---

export type UserStatus = 'active' | 'suspended';

export interface User {
  id: string; // Employee ID (e.g., A888)
  name: string;
  phone: string;
  todayUsage: number;
  status: UserStatus;
  avatarUrl?: string;
}

export interface AuditRecord {
  id: string;           // 記錄 ID（對應 Audit Sheet 的行號或唯一識別碼）
  userId: string;
  userName: string;
  timestamp: string;
  originalUrl: string;  // Google Drive 原圖分享連結
  resultUrl: string;    // Google Drive 結果圖分享連結
  fileName?: string;    // 原始檔名
  spaceType?: string;   // 空間類型（客廳、臥室等）
  mode?: string;        // 處理模式（eraser / staging）
  originalFileId?: string; // Drive 原圖檔案 ID（用於刪除）
  resultFileId?: string;   // Drive 結果圖檔案 ID（用於刪除）
}

export type SessionRole = 'admin' | 'user';

export interface SessionUser {
  id: string; // Employee ID (e.g., A888)
  name: string;
  role: SessionRole;
}
